server:
  port: 9001

spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://120.26.184.121:3306/user_center
    hikari:
      username: root
      password: abc.123
      driver-class-name: com.mysql.cj.jdbc.Driver



management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

