server:
  port: 9002
spring:
  application:
    name: syc-course-center
  zipkin:
    base-url: http://localhost:9411/
    discovery-client-enabled: false
    sleuth:
      sampler:
        probability: 1.0
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://120.26.184.121:3306/content_center?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    hikari:
      username: root
      password: abc.123
      driver-class-name: com.mysql.cj.jdbc.Driver
#      minimum-idle: 10
#      maximum-pool-size: 10
#      max-lifetime: 1800000
#      idle-timeout: 600000
#      connection-timeout: 30000
  cloud:
    nacos:
      discovery:
        server-addr: 123.56.91.23:8848
    sentinel:
      transport:
        dashboard: 123.56.91.23:8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
#      细粒度的配置方式，不支持全局配置文件式写法，Ribbon全局配置只能用Java代码配置
syc-user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    ReadTimeout: 30000
    ConnectTimeout: 30000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  eager-load:
    clients: syc-user-center
    enabled: true
#feign配置日志
logging:
  level:
    #feign的日志系统是建立在SpringBoot基础上，此处一定要是debug，否则都不会打印
    com.soft1851.contentcenter.feignclient.UserCenterFeignClient: debug
rocketmq:
  name-server: 123.56.91.23:9876
  producer:
    group: test-group
#feign细粒度配置
feign:
  sentinel:
#     为feign整合sentinel
    enabled: true
  client:
    config:
      default:
        loggerLevel: full
        requestInsterceptors:
          - com.soft1851.contentcenter.feignclient.interceptor.TokenInterceptor
  httpclient:
#    让feign使用apache httpclient做请求，而不是默认的urlconnection
    enabled: true
#    feign的最大连接数
    max-connections: 200
#    feign单个路径的最大连接数
    max-connections-per-route: 50
#  client:
#    config:
#      #      想要调用的微服务名称
#      user-center:
#        loggerLevel: full






